apiVersion: v1
kind: Service
metadata:
  name: nestjs-service
spec:
  selector:
    app.kubernetes.io/name: nestjs
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort:  {{ .Values.service.port }}
    #   nodePort: 32000
# https://kubernetes.docker.internal.nestjs-service.default.svc.cluster.local
# http://localhost:8080/api/v1/proxy/namespaces/default/services/nestjs-service:3000/ 