apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: nestjs-application-dev
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/amar141989-dev/prisma-pg-nest.git
    path: nest-chart
    targetRevision: main
    helm:
      valueFiles:
        - values.yaml
      parameters:
        - name: image.tag
          value: $ARGOCD_APP_REVISION
  destination:
    server: https://kubernetes.default.svc
    namespace: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true