replicaCount: 1

# This sets the container image more information can be found here: https://kubernetes.io/docs/concepts/containers/images/
image:
  repository: amar141989/nestjs
  # This sets the pull policy for images.
  pullPolicy: IfNotPresent
  # Overrides the image tag whose default is the chart appVersion.
  tag: "ec614a7487f6b13e28e0cc1cfe91b18d07af4a61"

autoscaling:
  enabled: true

service:
  port: 3000