name: Build and push to artifactory

on:
  push:
    branches:
      - main 

jobs:
  test: 
    runs-on: ubuntu-latest 
    steps:
      - name: Checkout the repository   
        uses: actions/checkout@v2
      
      - name: Set up Node.js (or any language you use)
        uses: actions/setup-node@v2
        with:
          node-version: '20'
      
      - name: Install dependencies 
        run: run install
      
      - name: Run tests 
        run: npm test
  
  build:
    runs-on: ubuntu-latest 
    # needs: test
    steps:
      - name: Checkout the repository 
        uses: actions/checkout@v2
      
      - name: Login to docker 
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Cache docker layers 
        uses: actions/cache@v2
        with:
          path: /tmp/.buildx-cache
          key: ${{ runner.os }}-buildx-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-buildx-
      
      - name: Build docker image 
        run: |
          docker buildx build --push --tag amar141989/nestjs:${{ github.sha }} .